### ISSUE TITLE
Syntex error using supermercado

### ISSUE THREAD

**Issue by manishsharma28** [mapbox/supermercado#32]
`cat val_aoi.geojson | supermercado burn 19 | mercantile shapes | fio collect > val_aoi_z19tiles.geojson`

File "<ipython-input-77-d1062140a391>", line 2
    cat val_aoi.geojson | supermercado burn 19 | mercantile shapes | fio collect > val_aoi_z19tiles.geojson
              ^
SyntaxError: invalid syntax

**Comment by sgillies** [comment]
@manishsharma28 that line of code isn't Python, it's a shell script. If you pass it to python, you must expect a syntax error.

**Comment by manishsharma28** [comment]
Could you please tell me a way to use this script in python.

**Comment by pratikyadav** [comment]
@manishsharma28  Supermercado is based on mercantile python module that you can use in your python script. Take a look at the docs here -> https://github.com/mapbox/mercantile

**Comment by manishsharma28** [comment]
@pratikyadav Thank you.
and this cmd is working by using "!type" instead of "cat" in python like:
!type file.geojson | supermercado burn 19 | mercantile shapes | fio collect > file_tiles.geojson
