### ISSUE TITLE
Missing coverage

### ISSUE THREAD

**Issue by zenonp** [mapbox/supermercado#54]
All three maps of Greece in README.md miss [Kastellorizo](https://www.openstreetmap.org/relation/5321397#map=8/36.142/29.583). This might suggest an edge-seeking error in the burn algorithm or something wrong with the input data.

**Comment by mappingvermont** [comment]
Thanks for raising this @zenonp!

It looks like Kastellorizo is not included in the [example input data](https://github.com/mapbox/supermercado/blob/main/data/ellada.geojson).

Please reopen if you think this is due to an underlying issue in the library 🙏
